// ===================================================
// AXIS ▪︎ VITE CONFIGURATION
// Configures server, build processes and HTML templating
// ===================================================

import { resolve } from "node:path";
import { defineConfig } from "vite";
import injectHTML from "vite-plugin-html-inject";

export default defineConfig({
  // == Plugins ==
  // Enables <load src="..."> syntax for HTML partials
  plugins: [injectHTML()],

  // == Base & Root ==
  // Base public path
  base: "/",

  // Root of the project — where index.html lives
  root: ".",

  // Static assets served as-is (copied to dist/ on build)
  publicDir: "public",

  // == Development Server ==
  server: {
    host: true,
    port: 3000,
    open: true,
  },

  // == Build Options ==
  build: {
    // Output folder (generated by `yarn build`)
    outDir: "dist",

    // Clears dist/ before each build
    emptyOutDir: true,

    // Sourcemaps for production debugging
    sourcemap: false,

    // Customize output structure and multi-page setup
    rollupOptions: {
      // Define entry points for multi-page architecture
      input: {
        main: resolve(import.meta.dirname, "index.html"),
        // Uncomment below to add more pages to the build process
        error: resolve(import.meta.dirname, "404.html"),
      },

      output: {
        // JavaScript files
        entryFileNames: "js/[name]-[hash].js",

        // Dynamic chunks
        chunkFileNames: "js/[name]-[hash].js",

        // Assets
        assetFileNames: ({ name }) => {
          // CSS files
          if (name?.endsWith(".css")) {
            return "css/[name]-[hash][extname]";
          }

          // Everything else keeps Vite's asset handling
          return "assets/[name]-[hash][extname]";
        },
      },
    },
  },

  // == CSS / Sass Settings ==
  css: {
    // Sourcemaps in development (helps debug Sass in DevTools)
    devSourcemap: true,
  },
});
