// ===================================================
// AXIS — VITE CONFIGURATION
// ===================================================
// vite.config.js tells Vite how to serve, build,
// and handle your project's assets and output.
// ===================================================

import { defineConfig } from "vite";

export default defineConfig({
  // Base public path
  base: "/",

  // Root of the project — where index.html lives
  root: ".",

  // Static assets served as-is (copied to dist/ on build)
  publicDir: "public",

  // Development server settings
  server: {
    host: true,
    port: 3000,
    open: true,
  },

  // Build output settings
  build: {
    // Output folder (generated by `npm run build`)
    outDir: "dist",

    // Clears dist/ before each build
    emptyOutDir: true,

    // Sourcemaps for production debugging
    sourcemap: false,

    // Customize output structure
    rollupOptions: {
      output: {
        // JavaScript files
        entryFileNames: "js/[name]-[hash].js",

        // Dynamic chunks
        chunkFileNames: "js/[name]-[hash].js",

        // Assets
        assetFileNames: ({ name }) => {
          // CSS files
          if (name?.endsWith(".css")) {
            return "css/[name]-[hash][extname]";
          }

          // Everything else keeps Vite's asset handling
          return "assets/[name]-[hash][extname]";
        },
      },
    },
  },

  // CSS / Sass settings
  css: {
    // Sourcemaps in development (helps debug Sass in DevTools)
    devSourcemap: true,
  },
});
